global:
  resolve_timeout: 1m

templates:
- 'wechat.tmpl'

route:
    receiver: 'wechat'

receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: "xxxxxxxxxxxxxxxxxxx" # 我的企业-->CorpId[在底部
    to_party: '2'
    agent_id: '1000002'   # 企业微信-->自定应用-->AgentId
    api_secret: "xxxxxxxxxxxxxxxxxxxxxxxxx" #企业微信-->自定应用-->Secret
    send_resolved: true
    message: '{{ template "wechat" . }}'
