version: "2.4"
services:
  rabbitmq:
    build: ./
    image: rabbitmq
    #image: rabbitmq:3.7.8-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE='628WB79CIFxxxxxxxxxL'
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=Abcd1234
      - RABBITMQ_HIPE_COMPILE=1
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MiB
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq-1
    restart: always
