version: "2.4"
services:
  gitlab:
     image: gitlab/gitlab-ce:11.4.4-ce.0
     container_name: gitlab
     restart: always
     hostname: 'gitlab'
     environment:
       GITLAB_OMNIBUS_CONFIG: |
         external_url 'http://192.168.1.1'
         gitlab_rails['backup_keep_time'] = 604800
         gitlab_rails['time_zone'] = 'Asia/Shanghai'
     ports:
       - '80:80'
       - '443:443'
       - '22:22'
     volumes:
       - /gitlab/config:/etc/gitlab
       - /gitlab/logs:/var/log/gitlab
       - /gitlab/data:/var/opt/gitlab
