version: "2.4"
services:
  ldap:
    image: mwaeckerlin/openldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    networks:
      - ldap
    volumes:
      - ldapconf:/etc/ldap
      - ldapssl:/ssl
      - ldapbackup:/var/backups
      - ldapdata:/var/lib/ldap
    environment:
      - DOMAIN=aworld.cn
      - ORGANIZATION="aworld"
      - PASSWORD=admin
      - DEBUG_LEVEL=0
    restart: always
    cpus: 1.5
    mem_limit: 1024m


  lam:
    image: mwaeckerlin/lam
    container_name: lam
    ports:
      - "80:80"
    networks:
      - ldap
    volumes:
      - lamconfig:/etc/ldap-account-manager
      - lamdata:/var/lib/ldap-account-manager
    restart: always
    cpus: 1
    mem_limit: 1024m

networks:
  ldap:
    driver: bridge
    name: ldap

volumes:
  ldapconf:
  ldapssl:
  ldapbackup:
  ldapdata:
  lamconfig:
  lamdata:
